import { Modal, notification, Button } from 'antd';
const Simulation = {};//，启动模拟数据


Simulation.GetDataDetail = () => {
  console.log("测试账号登陆，启动模拟数据=================");
  notification['info']({
    message: '提示',
    description: '功能为模拟数据！',
    duration: 1
  });
  var QueryTypeData ={
    result:true,
    data:{
      objectList:[
        {fieldid:"1",byname:"首批国医大师",favoritedesc:"首批国医大师"},
        {fieldid:"2",byname:"首批国医大师",favoritedesc:"首批国医大师"},
        {fieldid:"3",byname:"首批国医大师",favoritedesc:"首批国医大师"},
      ]
    }
  }
  return QueryTypeData;
};

Simulation.ImtreatprelistGetList = () => {
  console.log("测试账号登陆，启动模拟数据=================");
  notification['info']({
    message: '提示',
    description: '功能为模拟数据！',
    duration: 1
  });
  var QueryTypeData ={
      "msg": "获取处方列表成功",
      "flag": 1,
      "data": {
          "plist": {
              "current": 1,
              "dataList": [
                  {
                      "cpmId": 1,
                      "preName":"维C银翘片",
                      "createDate": 1534758871000,
                      "days": 3,
                      "therapy":"清暑祛湿解表",
                      "drugName": "栀子、金银花、黄芩、黄柏、大黄、黄连、知母、天花粉。",
                      "effect": "",
                      "freqid": 2,
                      "id": 148,
                      "itId": 79,
                      "modifyDate": 1534828259000,
                      "stars": 1,
                      "treatname": "æ\u0084\u009få\u0086\u0092\\æ\u009a\u0091æ¹¿ä¼¤è¡¨è¯\u0081",
                      "type": 2,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "cpmId": 2,
                      "preName":"维C银翘片",
                      "createDate": 1534758868000,
                      "days": 3,
                      "therapy":"清暑祛湿解表",
                      "drugName": "黄连、栀子、连翘、大黄、升麻、知母、当归、石膏、白芷、薄荷、玄参、黄芩、芒硝、牡丹皮、防风、生地黄、甘草、荆芥、赤芍、天花粉",
                      "effect": "",
                      "freqid": 2,
                      "id": 149,
                      "itId": 79,
                      "modifyDate": 1534828261000,
                      "stars": 1,
                      "treatname": "æ\u0084\u009få\u0086\u0092\\æ\u009a\u0091æ¹¿ä¼¤è¡¨è¯\u0081",
                      "type": 2,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "cpmId": 3,
                      "preName":"维C银翘片",
                      "createDate": 1534758865000,
                      "therapy":"清暑祛湿解表",
                      "days": 3,
                      "drugName": "黄连、黄柏、石膏、金银花、薄荷、桔梗、连翘、大黄、黄芩、栀子（姜炙）、菊花、荆芥穗、防风、旋复花、白芷、川芎、蔓荆子(微炒)、蚕砂、甘草、牛黄、冰片。",
                      "effect": "",
                      "freqid": 2,
                      "id": 150,
                      "itId": 79,
                      "modifyDate": 1534828262000,
                      "stars": 1,
                      "treatname": "æ\u0084\u009få\u0086\u0092\\æ\u009a\u0091æ¹¿ä¼¤è¡¨è¯\u0081",
                      "type": 2,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "cpmId": 4,
                      "preName":"维C银翘片",
                      "createDate": 1532595025000,
                      "therapy":"清暑祛湿解表",
                      "days": 2,
                      "drugName": "陈皮、甘草(蜜炙)、半夏(姜制)、生姜、茯苓。",
                      "effect": "123",
                      "freqid": 1,
                      "id": 151,
                      "itId": 79,
                      "modifyDate": 1534828263000,
                      "stars": 1,
                      "treatname": "æ\u0084\u009få\u0086\u0092\\æ\u009a\u0091æ¹¿ä¼¤è¡¨è¯\u0081",
                      "type": 2,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "cpmId": 5,
                      "preName":"维C银翘片",
                      "createDate": 1532598714000,
                      "therapy":"清暑祛湿解表",
                      "days": 4,
                      "drugName": "冬虫夏草、半夏(麸炒)、竹茹(麸炒)、枳实(麸炒)、陈皮、茯苓、石菖蒲、葛根、干姜、炙甘草",
                      "effect": "321",
                      "freqid": 3,
                      "id": 152,
                      "itId": 79,
                      "modifyDate": 1534828264000,
                      "stars": 1,
                      "treatname": "æ\u0084\u009få\u0086\u0092\\æ\u009a\u0091æ¹¿ä¼¤è¡¨è¯\u0081",
                      "type": 2,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "cpmId": 6,
                      "preName":"维C银翘片",
                      "createDate": 1534758862000,
                      "therapy":"清暑祛湿解表",
                      "days": 3,
                      "drugName": "鱼腥草、金荞麦、四季青、麻黄、紫菀、前胡、枳壳、甘草。\r\n",
                      "effect": "",
                      "freqid": 2,
                      "id": 153,
                      "itId": 79,
                      "modifyDate": 1534828265000,
                      "stars": 1,
                      "treatname": "æ\u0084\u009få\u0086\u0092\\æ\u009a\u0091æ¹¿ä¼¤è¡¨è¯\u0081",
                      "type": 2,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "cpmId": 7,
                      "preName":"维C银翘片",
                      "createDate": 1534758858000,
                      "therapy":"清暑祛湿解表",
                      "days": 3,
                      "drugName": "木香、砂仁、白术，陈皮，茯苓，半夏，香附，枳实，豆蔻，厚朴 姜制，广藿香，甘草",
                      "effect": "",
                      "freqid": 2,
                      "id": 154,
                      "itId": 79,
                      "modifyDate": 1534828266000,
                      "stars": 1,
                      "treatname": "æ\u0084\u009få\u0086\u0092\\æ\u009a\u0091æ¹¿ä¼¤è¡¨è¯\u0081",
                      "type": 2,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "cpmId": 9,
                      "preName":"维C银翘片",
                      "createDate": 1534758851000,
                      "therapy":"清暑祛湿解表",
                      "days": 2,
                      "drugName": "龙胆泻肝丸",
                      "effect": "",
                      "freqid": 1,
                      "id": 155,
                      "itId": 79,
                      "modifyDate": 1534828267000,
                      "stars": 1,
                      "treatname": "æ\u0084\u009få\u0086\u0092\\æ\u009a\u0091æ¹¿ä¼¤è¡¨è¯\u0081",
                      "type": 2,
                      "useflag": "1",
                      "visitCount": 0
                  }
              ],
              "pages": 5,
              "size": 8,
              "star": 0,
              "total": 39
          },
          "clist": {
              "current": 3,
              "dataList": [
                  {
                      "createDate": 1438768468000,
                      "preName":"维C银翘片",
                      "drugName": "人参,黄芪,肉桂,甘草,生姜",
                      "effect": "益气温阳，适用于阳虚气弱之证",
                      "therapy":"清暑祛湿解表",
                      "id": 130,
                      "itId": 66,
                      "preId": 420,
                      "preName": "保元汤加减",
                      "priors": "1",
                      "stars": 1,
                      "tcmImlistEntities": [
                          {
                              "createDate": 1438768486000,
                              "drugNamesList": "郁金(+),川穹(+),丹参(+),三七(+)",
                              "effect": "活血定痛",
                              "id": 229,
                              "ilId": 66,
                              "priors": 0,
                              "severity": "心胸疼痛者",
                              "tcmImpluslistEntities": [
                                  {
                                      "createDate": 1438768495000,
                                      "defQty": 0,
                                      "drugId": 408,
                                      "drugName": "郁金",
                                      "drugNameCap": "YJ",
                                      "id": 501,
                                      "lid": 229,
                                      "newDose": 4,
                                      "newRdose": 0,
                                      "status": "1",
                                      "unit": "g",
                                      "useflag": "1"
                                  },
                                  {
                                      "createDate": 1438768502000,
                                      "defQty": 0,
                                      "drugId": 590,
                                      "drugName": "川穹",
                                      "drugNameCap": "CQ",
                                      "id": 502,
                                      "lid": 229,
                                      "newDose": 4,
                                      "newRdose": 0,
                                      "status": "1",
                                      "unit": "g",
                                      "useflag": "1"
                                  },
                                  {
                                      "createDate": 1438768512000,
                                      "defQty": 0,
                                      "drugId": 417,
                                      "drugName": "丹参",
                                      "drugNameCap": "DC",
                                      "id": 503,
                                      "lid": 229,
                                      "newDose": 4,
                                      "newRdose": 0,
                                      "status": "1",
                                      "unit": "g",
                                      "useflag": "1"
                                  },
                                  {
                                      "createDate": 1438768516000,
                                      "defQty": 0,
                                      "drugId": 350,
                                      "drugName": "三七",
                                      "drugNameCap": "SQ",
                                      "id": 504,
                                      "lid": 229,
                                      "newDose": 4,
                                      "newRdose": 0,
                                      "status": "1",
                                      "unit": "g",
                                      "useflag": "1"
                                  }
                              ],
                              "useflag": "1"
                          },
                          {
                              "createDate": 1438768529000,
                              "drugNamesList": "附子(+),巴戟天(+),仙茅(+),仙灵脾(+),鹿茸(+)",
                              "effect": "温补阳气",
                              "id": 230,
                              "ilId": 66,
                              "priors": 0,
                              "severity": "形寒肢冷，为阳虚较甚",
                              "tcmImpluslistEntities": [
                                  {
                                      "createDate": 1438768536000,
                                      "defQty": 0,
                                      "drugId": 137,
                                      "drugName": "附子",
                                      "drugNameCap": "FZ",
                                      "id": 505,
                                      "lid": 230,
                                      "newDose": 4,
                                      "newRdose": 0,
                                      "status": "1",
                                      "unit": "g",
                                      "useflag": "1"
                                  },
                                  {
                                      "createDate": 1438768541000,
                                      "defQty": 0,
                                      "drugId": 225,
                                      "drugName": "巴戟天",
                                      "drugNameCap": "BJT",
                                      "id": 506,
                                      "lid": 230,
                                      "newDose": 4,
                                      "newRdose": 0,
                                      "status": "1",
                                      "unit": "g",
                                      "useflag": "1"
                                  },
                                  {
                                      "createDate": 1438768545000,
                                      "defQty": 0,
                                      "drugId": 226,
                                      "drugName": "仙茅",
                                      "drugNameCap": "XM",
                                      "id": 507,
                                      "lid": 230,
                                      "newDose": 4,
                                      "newRdose": 0,
                                      "status": "1",
                                      "unit": "g",
                                      "useflag": "1"
                                  },
                                  {
                                      "createDate": 1438768551000,
                                      "defQty": 0,
                                      "drugId": 853,
                                      "drugName": "仙灵脾",
                                      "drugNameCap": "XLP",
                                      "id": 508,
                                      "lid": 230,
                                      "newDose": 4,
                                      "newRdose": 0,
                                      "status": "1",
                                      "unit": "g",
                                      "useflag": "1"
                                  },
                                  {
                                      "createDate": 1438768557000,
                                      "defQty": 0,
                                      "drugId": 159,
                                      "drugName": "鹿茸",
                                      "drugNameCap": "LR",
                                      "id": 509,
                                      "lid": 230,
                                      "newDose": 4,
                                      "newRdose": 0,
                                      "status": "1",
                                      "unit": "g",
                                      "useflag": "1"
                                  }
                              ],
                              "useflag": "1"
                          }
                      ],
                      "tcmPrelistEntities": [
                          {
                              "createDate": 1438768433000,
                              "defQty": 0,
                              "drugId": 454,
                              "drugName": "人参",
                              "exist": 0,
                              "id": 2860,
                              "modifyDate": 1450240518000,
                              "nameCap": "RS",
                              "newDose": 9,
                              "newrDose": 0,
                              "oldDose": "",
                              "pId": 420,
                              "remarks": "",
                              "unit": "g"
                          },
                          {
                              "createDate": 1438768438000,
                              "defQty": 0,
                              "drugId": 473,
                              "drugName": "黄芪",
                              "exist": 0,
                              "id": 2861,
                              "modifyDate": 1450240523000,
                              "nameCap": "HQ",
                              "newDose": 18,
                              "newrDose": 0,
                              "oldDose": "",
                              "pId": 420,
                              "remarks": "",
                              "unit": "g"
                          },
                          {
                              "createDate": 1438768443000,
                              "defQty": 0,
                              "drugId": 140,
                              "drugName": "肉桂",
                              "exist": 0,
                              "id": 2862,
                              "modifyDate": 1450240535000,
                              "nameCap": "RG",
                              "newDose": 5,
                              "newrDose": 0,
                              "oldDose": "",
                              "pId": 420,
                              "remarks": "",
                              "unit": "g"
                          },
                          {
                              "createDate": 1438768447000,
                              "defQty": 0,
                              "drugId": 489,
                              "drugName": "甘草",
                              "exist": 0,
                              "id": 2863,
                              "modifyDate": 1450240540000,
                              "nameCap": "GC",
                              "newDose": 6,
                              "newrDose": 0,
                              "oldDose": "",
                              "pId": 420,
                              "remarks": "",
                              "unit": "g"
                          },
                          {
                              "createDate": 1438768452000,
                              "defQty": 0,
                              "drugId": 7,
                              "drugName": "生姜",
                              "exist": 0,
                              "id": 2864,
                              "modifyDate": 1450240547000,
                              "nameCap": "SJ",
                              "newDose": 6,
                              "newrDose": 0,
                              "oldDose": "",
                              "pId": 420,
                              "remarks": "",
                              "unit": "g"
                          }
                      ],
                      "treatname": "è\u0099\u009aå\u008a³\\å¿\u0083é\u0098³è\u0099\u009aè¯\u0081",
                      "type": 1,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "createDate": 1437719415000,
                      "preName":"维C银翘片",
                      "therapy":"清暑祛湿解表",
                      "drugName": "黄连末,天花粉,生地汁,藕汁,人乳汁,姜汁,蜂蜜",
                      "effect": "清热降火，生津止渴，适用于消渴肺热津伤之证",
                      "freqid": 3,
                      "id": 6,
                      "itId": 5,
                      "modifyDate": 1534382520000,
                      "preId": 342,
                      "preName": "消渴方",
                      "priors": "0",
                      "stars": 1,
                      "tcmPrelistEntities": [
                          {
                              "createDate": 1438830736000,
                              "defQty": 0,
                              "drugId": 923,
                              "drugName": "黄连末",
                              "exist": 0,
                              "id": 3288,
                              "modifyDate": 1449835840000,
                              "nameCap": "HLM",
                              "newDose": 5,
                              "newrDose": 0,
                              "pId": 342,
                              "unit": "g"
                          },
                          {
                              "createDate": 1438830743000,
                              "defQty": 0,
                              "drugId": 75,
                              "drugName": "天花粉",
                              "exist": 0,
                              "id": 3289,
                              "modifyDate": 1450273465000,
                              "nameCap": "THF",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 342,
                              "unit": "g"
                          },
                          {
                              "createDate": 1438830754000,
                              "defQty": 0,
                              "drugId": 876,
                              "drugName": "生地汁",
                              "exist": 0,
                              "id": 3290,
                              "modifyDate": 1450273536000,
                              "nameCap": "SDZ",
                              "newDose": 9,
                              "newrDose": 0,
                              "pId": 342,
                              "unit": "g"
                          },
                          {
                              "createDate": 1438830759000,
                              "defQty": 0,
                              "drugId": 882,
                              "drugName": "藕汁",
                              "exist": 0,
                              "id": 3291,
                              "modifyDate": 1450273531000,
                              "nameCap": "OZ",
                              "newDose": 9,
                              "newrDose": 0,
                              "pId": 342,
                              "unit": "g"
                          },
                          {
                              "createDate": 1438830763000,
                              "defQty": 0,
                              "drugId": 878,
                              "drugName": "人乳汁",
                              "exist": 0,
                              "id": 3292,
                              "modifyDate": 1450273524000,
                              "nameCap": "RRZ",
                              "newDose": 9,
                              "newrDose": 0,
                              "pId": 342,
                              "unit": "g"
                          },
                          {
                              "createDate": 1438830770000,
                              "defQty": 0,
                              "drugId": 741,
                              "drugName": "姜汁",
                              "exist": 0,
                              "id": 3293,
                              "modifyDate": 1450273504000,
                              "nameCap": "JZ",
                              "newDose": 9,
                              "newrDose": 0,
                              "pId": 342,
                              "unit": "g"
                          },
                          {
                              "createDate": 1438830774000,
                              "defQty": 0,
                              "drugId": 505,
                              "drugName": "蜂蜜",
                              "exist": 0,
                              "id": 3294,
                              "modifyDate": 1450273481000,
                              "nameCap": "FM",
                              "newDose": 30,
                              "newrDose": 0,
                              "pId": 342,
                              "unit": "g"
                          }
                      ],
                      "treatname": "æ¶\u0088æ¸´\\è\u0082ºç\u0083\u00adæ´¥ä¼¤è¯\u0081",
                      "type": 1,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "createDate": 1438753531000,
                      "preName":"维C银翘片",
                      "therapy":"清暑祛湿解表",
                      "drugName": "天花粉,葛根,麦冬,生地,藕汁,黄连,黄芩,知母",
                      "effect": "清热降火，生津止渴，适用于消渴肺热津伤之证",
                      "freqid": 3,
                      "id": 63,
                      "itId": 5,
                      "modifyDate": 1534382619000,
                      "preId": 373,
                      "preName": "消渴方加减",
                      "priors": "1",
                      "stars": 1,
                      "tcmImlistEntities": [
                          {
                              "createDate": 1437720033000,
                              "drugNamesList": "",
                              "effect": "清热生津止渴，益气作用较强",
                              "id": 8,
                              "ilId": 5,
                              "modifyDate": 1438753178000,
                              "prename": "玉泉丸",
                              "priors": 0,
                              "severity": "烦渴不止，小便频数，而脉数乏力者，为肺热津亏，气阴两伤",
                              "tcmImpluslistEntities": [],
                              "useflag": "1"
                          },
                          {
                              "createDate": 1437720063000,
                              "drugNamesList": "",
                              "effect": "清热生津止渴，清热作用较强",
                              "id": 9,
                              "ilId": 5,
                              "modifyDate": 1438753316000,
                              "prename": "二冬汤",
                              "priors": 0,
                              "severity": "烦渴不止，小便频数，而脉数乏力者，为肺热津亏，气阴两伤",
                              "tcmImpluslistEntities": [],
                              "useflag": "1"
                          }
                      ],
                      "tcmPrelistEntities": [
                          {
                              "createDate": 1438753461000,
                              "defQty": 0,
                              "drugId": 75,
                              "drugName": "天花粉",
                              "exist": 0,
                              "id": 2485,
                              "modifyDate": 1450188808000,
                              "nameCap": "THF",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 373,
                              "unit": "g"
                          },
                          {
                              "createDate": 1438753466000,
                              "defQty": 0,
                              "drugId": 55,
                              "drugName": "葛根",
                              "exist": 0,
                              "id": 2486,
                              "modifyDate": 1450188814000,
                              "nameCap": "GG",
                              "newDose": 15,
                              "newrDose": 0,
                              "pId": 373,
                              "unit": "g"
                          },
                          {
                              "createDate": 1438753471000,
                              "defQty": 0,
                              "drugId": 474,
                              "drugName": "麦冬",
                              "exist": 0,
                              "id": 2487,
                              "modifyDate": 1450188818000,
                              "nameCap": "MD",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 373,
                              "unit": "g"
                          },
                          {
                              "createDate": 1438753477000,
                              "defQty": 0,
                              "drugId": 615,
                              "drugName": "生地",
                              "exist": 0,
                              "id": 2488,
                              "modifyDate": 1450188823000,
                              "nameCap": "SD",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 373,
                              "unit": "g"
                          },
                          {
                              "createDate": 1438753483000,
                              "defQty": 0,
                              "drugId": 882,
                              "drugName": "藕汁",
                              "exist": 0,
                              "id": 2489,
                              "modifyDate": 1450188828000,
                              "nameCap": "OZ",
                              "newDose": 9,
                              "newrDose": 0,
                              "pId": 373,
                              "unit": "g"
                          },
                          {
                              "createDate": 1438753492000,
                              "defQty": 0,
                              "drugId": 112,
                              "drugName": "黄连",
                              "exist": 0,
                              "id": 2490,
                              "modifyDate": 1450188832000,
                              "nameCap": "HL",
                              "newDose": 5,
                              "newrDose": 0,
                              "pId": 373,
                              "unit": "g"
                          },
                          {
                              "createDate": 1438753500000,
                              "defQty": 0,
                              "drugId": 109,
                              "drugName": "黄芩",
                              "exist": 0,
                              "id": 2491,
                              "modifyDate": 1450188838000,
                              "nameCap": "HQ",
                              "newDose": 9,
                              "newrDose": 0,
                              "pId": 373,
                              "unit": "g"
                          },
                          {
                              "createDate": 1438753504000,
                              "defQty": 0,
                              "drugId": 72,
                              "drugName": "知母",
                              "exist": 0,
                              "id": 2492,
                              "modifyDate": 1450188842000,
                              "nameCap": "ZM",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 373,
                              "unit": "g"
                          }
                      ],
                      "treatname": "æ¶\u0088æ¸´\\è\u0082ºç\u0083\u00adæ´¥ä¼¤è¯\u0081",
                      "type": 1,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "createDate": 1441019792000,
                      "preName":"维C银翘片",
                      "therapy":"清暑祛湿解表",
                      "drugName": "菟丝子,人参,熟地黄,山药,山茱萸,远志,灸甘草,五味子",
                      "effect": "",
                      "id": 2007,
                      "itId": 5,
                      "modifyDate": 1534842562000,
                      "preId": 925,
                      "preName": "固阴煎",
                      "priors": "1",
                      "stars": 1,
                      "tcmImlistEntities": [
                          {
                              "$ref": "$.data.clist.dataList[2].tcmImlistEntities[0]"
                          },
                          {
                              "$ref": "$.data.clist.dataList[2].tcmImlistEntities[1]"
                          }
                      ],
                      "tcmPrelistEntities": [
                          {
                              "createDate": 1440830029000,
                              "defQty": 0,
                              "drugId": 372,
                              "drugName": "菟丝子",
                              "exist": 0,
                              "id": 7419,
                              "modifyDate": 1450167308000,
                              "nameCap": "TSZ",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 925,
                              "unit": "g"
                          },
                          {
                              "createDate": 1440830034000,
                              "defQty": 0,
                              "drugId": 454,
                              "drugName": "人参",
                              "exist": 0,
                              "id": 7420,
                              "modifyDate": 1450167311000,
                              "nameCap": "RS",
                              "newDose": 9,
                              "newrDose": 0,
                              "pId": 925,
                              "unit": "g"
                          },
                          {
                              "createDate": 1440830038000,
                              "defQty": 0,
                              "drugId": 459,
                              "drugName": "熟地黄",
                              "exist": 0,
                              "id": 7421,
                              "modifyDate": 1450167314000,
                              "nameCap": "SDH",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 925,
                              "unit": "g"
                          },
                          {
                              "createDate": 1440830042000,
                              "defQty": 0,
                              "drugId": 479,
                              "drugName": "山药",
                              "exist": 0,
                              "id": 7422,
                              "modifyDate": 1450167317000,
                              "nameCap": "SY",
                              "newDose": 15,
                              "newrDose": 0,
                              "pId": 925,
                              "unit": "g"
                          },
                          {
                              "createDate": 1440830048000,
                              "defQty": 0,
                              "drugId": 515,
                              "drugName": "山茱萸",
                              "exist": 0,
                              "id": 7423,
                              "modifyDate": 1450167319000,
                              "nameCap": "SZY",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 925,
                              "unit": "g"
                          },
                          {
                              "createDate": 1440830054000,
                              "defQty": 0,
                              "drugId": 399,
                              "drugName": "远志",
                              "exist": 0,
                              "id": 7424,
                              "modifyDate": 1450167326000,
                              "nameCap": "YZ",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 925,
                              "unit": "g"
                          },
                          {
                              "createDate": 1440830059000,
                              "defQty": 0,
                              "drugId": 976,
                              "drugName": "灸甘草",
                              "exist": 0,
                              "id": 7425,
                              "modifyDate": 1450167330000,
                              "nameCap": "JGC",
                              "newDose": 9,
                              "newrDose": 0,
                              "pId": 925,
                              "unit": "g"
                          },
                          {
                              "createDate": 1440830063000,
                              "defQty": 0,
                              "drugId": 503,
                              "drugName": "五味子",
                              "exist": 0,
                              "id": 7426,
                              "modifyDate": 1450167336000,
                              "nameCap": "WWZ",
                              "newDose": 6,
                              "newrDose": 0,
                              "pId": 925,
                              "unit": "g"
                          }
                      ],
                      "treatname": "æ¶\u0088æ¸´\\è\u0082ºç\u0083\u00adæ´¥ä¼¤è¯\u0081",
                      "type": 1,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "createDate": 1441020186000,
                      "preName":"维C银翘片",
                      "therapy":"清暑祛湿解表",
                      "drugName": "白术,茯神,黄芪,龙眼肉,酸枣仁,人参,木  香,甘草,当归,远志",
                      "effect": "",
                      "id": 2008,
                      "itId": 5,
                      "modifyDate": 1534842562000,
                      "preId": 16,
                      "preName": "归脾汤",
                      "priors": "1",
                      "stars": 1,
                      "tcmImlistEntities": [
                          {
                              "$ref": "$.data.clist.dataList[2].tcmImlistEntities[0]"
                          },
                          {
                              "$ref": "$.data.clist.dataList[2].tcmImlistEntities[1]"
                          }
                      ],
                      "tcmPrelistEntities": [
                          {
                              "createDate": 1436353532000,
                              "defQty": 0,
                              "drugId": 477,
                              "drugName": "白术",
                              "exist": 0,
                              "id": 69,
                              "modifyDate": 1450358608000,
                              "nameCap": "BZ",
                              "newDose": 18,
                              "newrDose": 0,
                              "oldDose": "一两",
                              "pId": 16,
                              "unit": "g"
                          },
                          {
                              "createDate": 1436353595000,
                              "defQty": 0,
                              "drugId": 200,
                              "drugName": "茯神",
                              "exist": 0,
                              "id": 71,
                              "modifyDate": 1450358616000,
                              "nameCap": "FS",
                              "newDose": 18,
                              "newrDose": 0,
                              "oldDose": "一两",
                              "pId": 16,
                              "remarks": "去木",
                              "unit": "g"
                          },
                          {
                              "createDate": 1436353640000,
                              "defQty": 0,
                              "drugId": 473,
                              "drugName": "黄芪",
                              "exist": 0,
                              "id": 72,
                              "nameCap": "HQ",
                              "newDose": 18,
                              "newrDose": 0,
                              "oldDose": "一两",
                              "pId": 16,
                              "remarks": "去芦",
                              "unit": "g"
                          },
                          {
                              "createDate": 1436353692000,
                              "defQty": 0,
                              "drugId": 463,
                              "drugName": "龙眼肉",
                              "exist": 0,
                              "id": 73,
                              "modifyDate": 1450358622000,
                              "nameCap": "LYR",
                              "newDose": 18,
                              "newrDose": 0,
                              "oldDose": "一两",
                              "pId": 16,
                              "unit": "g"
                          },
                          {
                              "createDate": 1436353726000,
                              "defQty": 0,
                              "drugId": 392,
                              "drugName": "酸枣仁",
                              "exist": 0,
                              "id": 75,
                              "modifyDate": 1450358627000,
                              "nameCap": "SZR",
                              "newDose": 18,
                              "newrDose": 0,
                              "oldDose": "一两",
                              "pId": 16,
                              "remarks": "炒，去壳",
                              "unit": "g"
                          },
                          {
                              "createDate": 1436353755000,
                              "defQty": 0,
                              "drugId": 454,
                              "drugName": "人参",
                              "exist": 0,
                              "id": 76,
                              "nameCap": "RS",
                              "newDose": 9,
                              "newrDose": 0,
                              "oldDose": "半两",
                              "pId": 16,
                              "unit": "g"
                          },
                          {
                              "createDate": 1436353794000,
                              "defQty": 0,
                              "drugId": 237,
                              "drugName": "木  香",
                              "exist": 0,
                              "id": 77,
                              "nameCap": "MX",
                              "newDose": 9,
                              "newrDose": 0,
                              "oldDose": "半两",
                              "pId": 16,
                              "remarks": "不见火",
                              "unit": "g"
                          },
                          {
                              "createDate": 1436353837000,
                              "defQty": 0,
                              "drugId": 489,
                              "drugName": "甘草",
                              "exist": 0,
                              "id": 81,
                              "nameCap": "GC",
                              "newDose": 6,
                              "newrDose": 0,
                              "oldDose": "二钱半",
                              "pId": 16,
                              "remarks": "炙",
                              "unit": "g"
                          },
                          {
                              "createDate": 1436353908000,
                              "defQty": 0,
                              "drugId": 458,
                              "drugName": "当归",
                              "exist": 0,
                              "id": 83,
                              "modifyDate": 1450358641000,
                              "nameCap": "DG",
                              "newDose": 3,
                              "newrDose": 0,
                              "oldDose": "一钱",
                              "pId": 16,
                              "unit": "g"
                          },
                          {
                              "createDate": 1436354017000,
                              "defQty": 0,
                              "drugId": 399,
                              "drugName": "远志",
                              "exist": 0,
                              "id": 86,
                              "modifyDate": 1450358645000,
                              "nameCap": "YZ",
                              "newDose": 3,
                              "newrDose": 0,
                              "oldDose": "一钱",
                              "pId": 16,
                              "unit": "g"
                          }
                      ],
                      "treatname": "æ¶\u0088æ¸´\\è\u0082ºç\u0083\u00adæ´¥ä¼¤è¯\u0081",
                      "type": 1,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "createDate": 1441020530000,
                      "preName":"维C银翘片",
                      "therapy":"清暑祛湿解表",
                      "drugName": "甘草,当归,茯苓,芍药,白术,柴胡",
                      "effect": "",
                      "id": 2009,
                      "itId": 5,
                      "modifyDate": 1534842562000,
                      "preId": 198,
                      "preName": "逍遥散",
                      "priors": "1",
                      "stars": 1,
                      "tcmImlistEntities": [
                          {
                              "$ref": "$.data.clist.dataList[2].tcmImlistEntities[0]"
                          },
                          {
                              "$ref": "$.data.clist.dataList[2].tcmImlistEntities[1]"
                          }
                      ],
                      "tcmPrelistEntities": [
                          {
                              "createDate": 1436527367000,
                              "defQty": 0,
                              "drugId": 489,
                              "drugName": "甘草",
                              "exist": 0,
                              "id": 1410,
                              "nameCap": "GC",
                              "newDose": 4,
                              "newrDose": 0,
                              "oldDose": "半两",
                              "pId": 198,
                              "remarks": "微炙赤",
                              "unit": "g"
                          },
                          {
                              "createDate": 1436527401000,
                              "defQty": 0,
                              "drugId": 458,
                              "drugName": "当归",
                              "exist": 0,
                              "id": 1411,
                              "modifyDate": 1436527419000,
                              "nameCap": "DG",
                              "newDose": 9,
                              "newrDose": 0,
                              "oldDose": "一两",
                              "pId": 198,
                              "remarks": "去苗，锉，微炒",
                              "unit": "g"
                          },
                          {
                              "createDate": 1436527452000,
                              "defQty": 0,
                              "drugId": 196,
                              "drugName": "茯苓",
                              "exist": 0,
                              "id": 1412,
                              "nameCap": "FL",
                              "newDose": 9,
                              "newrDose": 0,
                              "oldDose": "一两",
                              "pId": 198,
                              "remarks": "去皮，白者",
                              "unit": "g"
                          },
                          {
                              "createDate": 1436527511000,
                              "defQty": 0,
                              "drugId": 555,
                              "drugName": "芍药",
                              "exist": 0,
                              "id": 1413,
                              "nameCap": "SY",
                              "newDose": 9,
                              "newrDose": 0,
                              "oldDose": "一两",
                              "pId": 198,
                              "remarks": "白者",
                              "unit": "g"
                          },
                          {
                              "createDate": 1436527534000,
                              "defQty": 0,
                              "drugId": 477,
                              "drugName": "白术",
                              "exist": 0,
                              "id": 1414,
                              "nameCap": "BZ",
                              "newDose": 9,
                              "newrDose": 0,
                              "oldDose": "一两",
                              "pId": 198,
                              "unit": "g"
                          },
                          {
                              "createDate": 1436527556000,
                              "defQty": 0,
                              "drugId": 45,
                              "drugName": "柴胡",
                              "exist": 0,
                              "id": 1415,
                              "nameCap": "CH",
                              "newDose": 9,
                              "newrDose": 0,
                              "oldDose": "一两",
                              "pId": 198,
                              "remarks": "去苗",
                              "unit": "g"
                          }
                      ],
                      "treatname": "æ¶\u0088æ¸´\\è\u0082ºç\u0083\u00adæ´¥ä¼¤è¯\u0081",
                      "type": 1,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "createDate": 1441021198000,
                      "preName":"维C银翘片",
                      "therapy":"清暑祛湿解表",
                      "drugName": "茜草根,续断,白术,黄芪,生龙骨,生牡蛎,生地黄,白芍药,海螵蛸",
                      "effect": "方中黄芪、白术、升麻补气升提，固冲摄血；生龙骨、生牡蛎、海螵蛸、续断固冲 收敛止血；生地黄、白芍药凉血敛阴；茜草根止血而不留瘀。全方共奏补气升提、固冲 止血之效",
                      "id": 2010,
                      "itId": 5,
                      "modifyDate": 1534842562000,
                      "preId": 974,
                      "preName": "安冲汤",
                      "priors": "1",
                      "stars": 1,
                      "tcmImlistEntities": [
                          {
                              "$ref": "$.data.clist.dataList[2].tcmImlistEntities[0]"
                          },
                          {
                              "$ref": "$.data.clist.dataList[2].tcmImlistEntities[1]"
                          }
                      ],
                      "tcmPrelistEntities": [
                          {
                              "createDate": 1441021115000,
                              "defQty": 0,
                              "drugId": 477,
                              "drugName": "白术",
                              "exist": 0,
                              "id": 7801,
                              "modifyDate": 1450162344000,
                              "nameCap": "BZ",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 974,
                              "unit": "g"
                          },
                          {
                              "createDate": 1441021120000,
                              "defQty": 0,
                              "drugId": 473,
                              "drugName": "黄芪",
                              "exist": 0,
                              "id": 7802,
                              "modifyDate": 1450162347000,
                              "nameCap": "HQ",
                              "newDose": 18,
                              "newrDose": 0,
                              "pId": 974,
                              "unit": "g"
                          },
                          {
                              "createDate": 1441021128000,
                              "defQty": 0,
                              "drugId": 693,
                              "drugName": "生龙骨",
                              "exist": 0,
                              "id": 7803,
                              "modifyDate": 1450337710000,
                              "nameCap": "SLG",
                              "newDose": 20,
                              "newrDose": 0,
                              "pId": 974,
                              "unit": "g"
                          },
                          {
                              "createDate": 1441021141000,
                              "defQty": 0,
                              "drugId": 694,
                              "drugName": "生牡蛎",
                              "exist": 0,
                              "id": 7804,
                              "modifyDate": 1450337715000,
                              "nameCap": "SML",
                              "newDose": 20,
                              "newrDose": 0,
                              "pId": 974,
                              "unit": "g"
                          },
                          {
                              "createDate": 1441021146000,
                              "defQty": 0,
                              "drugId": 222,
                              "drugName": "生地黄",
                              "exist": 0,
                              "id": 7805,
                              "modifyDate": 1450162371000,
                              "nameCap": "SDH",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 974,
                              "unit": "g"
                          },
                          {
                              "createDate": 1441021154000,
                              "defQty": 0,
                              "drugId": 1129,
                              "drugName": "白芍药",
                              "exist": 0,
                              "id": 7806,
                              "modifyDate": 1450162373000,
                              "nameCap": "BSY",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 974,
                              "unit": "g"
                          },
                          {
                              "createDate": 1441021161000,
                              "defQty": 0,
                              "drugId": 519,
                              "drugName": "海螵蛸",
                              "exist": 0,
                              "id": 7807,
                              "modifyDate": 1450337725000,
                              "nameCap": "HPX",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 974,
                              "unit": "g"
                          },
                          {
                              "createDate": 1441021171000,
                              "defQty": 0,
                              "drugId": 950,
                              "drugName": "茜草根",
                              "exist": 0,
                              "id": 7808,
                              "modifyDate": 1450162386000,
                              "nameCap": "QCG",
                              "newDose": 9,
                              "newrDose": 0,
                              "pId": 974,
                              "unit": "g"
                          },
                          {
                              "createDate": 1441021177000,
                              "defQty": 0,
                              "drugId": 279,
                              "drugName": "续断",
                              "exist": 0,
                              "id": 7809,
                              "modifyDate": 1450162393000,
                              "nameCap": "XD",
                              "newDose": 9,
                              "newrDose": 0,
                              "pId": 974,
                              "unit": "g"
                          }
                      ],
                      "treatname": "æ¶\u0088æ¸´\\è\u0082ºç\u0083\u00adæ´¥ä¼¤è¯\u0081",
                      "type": 1,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "createDate": 1441021969000,
                      "preName":"维C银翘片",
                      "therapy":"清暑祛湿解表",
                      "drugName": "生地黄,熟地黄,黄芩,黄柏,白芍药,山药,续断",
                      "effect": "方中黄芩、黄柏、生地黄清热凉血；熟地黄、白芍药养血敛阴；山药、续断补肾固 冲；炒地榆、槐花凉血止血；甘草调和诸药。全方共奏清热凉血、固冲止血之效",
                      "id": 2011,
                      "itId": 5,
                      "modifyDate": 1534842562000,
                      "preId": 853,
                      "preName": "保阴煎",
                      "priors": "1",
                      "stars": 1,
                      "tcmImlistEntities": [
                          {
                              "$ref": "$.data.clist.dataList[2].tcmImlistEntities[0]"
                          },
                          {
                              "$ref": "$.data.clist.dataList[2].tcmImlistEntities[1]"
                          }
                      ],
                      "tcmPrelistEntities": [
                          {
                              "createDate": 1440763308000,
                              "defQty": 0,
                              "drugId": 222,
                              "drugName": "生地黄",
                              "exist": 0,
                              "id": 6825,
                              "modifyDate": 1450189486000,
                              "nameCap": "SDH",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 853,
                              "unit": "g"
                          },
                          {
                              "createDate": 1440763315000,
                              "defQty": 0,
                              "drugId": 459,
                              "drugName": "熟地黄",
                              "exist": 0,
                              "id": 6826,
                              "modifyDate": 1450191638000,
                              "nameCap": "SDH",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 853,
                              "unit": "g"
                          },
                          {
                              "createDate": 1440763320000,
                              "defQty": 0,
                              "drugId": 109,
                              "drugName": "黄芩",
                              "exist": 0,
                              "id": 6827,
                              "modifyDate": 1450191640000,
                              "nameCap": "HQ",
                              "newDose": 9,
                              "newrDose": 0,
                              "pId": 853,
                              "unit": "g"
                          },
                          {
                              "createDate": 1440763326000,
                              "defQty": 0,
                              "drugId": 129,
                              "drugName": "黄柏",
                              "exist": 0,
                              "id": 6828,
                              "modifyDate": 1450191642000,
                              "nameCap": "HB",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 853,
                              "unit": "g"
                          },
                          {
                              "createDate": 1440763331000,
                              "defQty": 0,
                              "drugId": 1129,
                              "drugName": "白芍药",
                              "exist": 0,
                              "id": 6829,
                              "modifyDate": 1450191645000,
                              "nameCap": "BSY",
                              "newDose": 12,
                              "newrDose": 0,
                              "pId": 853,
                              "unit": "g"
                          },
                          {
                              "createDate": 1440763336000,
                              "defQty": 0,
                              "drugId": 479,
                              "drugName": "山药",
                              "exist": 0,
                              "id": 6830,
                              "modifyDate": 1450191668000,
                              "nameCap": "SY",
                              "newDose": 15,
                              "newrDose": 0,
                              "pId": 853,
                              "unit": "g"
                          },
                          {
                              "createDate": 1440763341000,
                              "defQty": 0,
                              "drugId": 279,
                              "drugName": "续断",
                              "exist": 0,
                              "id": 6831,
                              "modifyDate": 1450191671000,
                              "nameCap": "XD",
                              "newDose": 9,
                              "newrDose": 0,
                              "pId": 853,
                              "unit": "g"
                          }
                      ],
                      "treatname": "æ¶\u0088æ¸´\\è\u0082ºç\u0083\u00adæ´¥ä¼¤è¯\u0081",
                      "type": 1,
                      "useflag": "1",
                      "visitCount": 0
                  }
              ],
              "pages": 4,
              "size": 8,
              "star": 16,
              "total": 28
          },
          "slist": {
              "current": 1,
              "dataList": [
                  {
                      "attention": "\"目前常用的罐具种类很多，如：竹罐、陶罐、玻璃罐和抽气罐等。 拔罐方法有火罐法、煮罐法、抽气罐法等，其中火罐法最为常用。 操作时用镊子夹住95%的酒精棉球，点燃后在罐内绕 1~3圈再抽出，并迅速将罐子扣在应拔的部位上。这种方法比较安全，但须注意的是点燃的酒精棉球切勿将罐口烧热，以免烫伤皮肤。\r\n根据病情需要，在具体运用火罐时，还有留罐、走罐、闪罐、刺血（刺络）拔罐等方法（具体操作可参照孙国杰主编《针灸学》的相关章节）。\"\r\n",
                      "days": 3,
                      "therapy":"清暑祛湿解表",
                      "effect": "拔罐法是以罐为工具，借助热力排除罐内空气，造成负压，使之吸附于腧穴或应拔部位的体表，使局部皮肤充血、瘀血，以达到防治疾病的目的。 常用于感冒、头痛、不寐、肩凝症、腰痛病、项痹病、胃脘痛病、痛经及带状疱疹等疾病。\r\n",
                      "freqid": 1,
                      "id": 1,
                      "itId": 79,
                      "modifyDate": 1534759386000,
                      "orgCode": "bg",
                      "position": "背部、肩部",
                      "stId": 3,
                      "stName": "拔罐",
                      "stars": 1,
                      "tcmImtreatprelistStAcupoints": [],
                      "tcmMatchingAcupoints": [],
                      "therapy": "\"1、留罐\r\n拔罐后将罐子吸拔留置在施术部位5~10分钟， 然后将罐起下。\r\n2、走罐\r\n一般用于面积较大、肌肉丰厚的部位，如腰背部、大腿部等。 一般选用口径较大的玻璃罐，先在罐口或欲拔罐部位涂一些凡士林油膏、液体石蜡等润滑剂，再将罐拔住，然后用右手握住罐子，上下往返推移，至所拔部位皮肤潮红、充血甚或瘀血时，将罐起下。\r\n3、闪罐\r\n将罐拔住后，又立即取下，再迅速拔住，如此反复多次地拔上起下，起下再拔，直至皮肤潮红为度。\r\n4、刺络拔罐\r\n将应拔部位的皮肤消毒后， 用三棱针点刺出血或用皮肤针叩刺，然后将火罐吸拔在点刺的部位上，使之出血，加强刺血治疗的作用。 一般针后拔罐留置5~10分钟。\r\n1、留罐\r\n拔罐后将罐子吸拔留置在施术部位5~10分钟， 然后将罐起下。\r\n2、走罐\r\n一般用于面积较大、肌肉丰厚的部位，如腰背部、大腿部等。 一般选用口径较大的玻璃罐，先在罐口或欲拔罐部位涂一些凡士林油膏、液体石蜡等润滑剂，再将罐拔住，然后用右手握住罐子，上下往返推移，至所拔部位皮肤潮红、充血甚或瘀血时，将罐起下。\r\n3、闪罐\r\n将罐拔住后，又立即取下，再迅速拔住，如此反复多次地拔上起下，起下再拔，直至皮肤潮红为度。\r\n4、刺络拔罐\r\n将应拔部位的皮肤消毒后， 用三棱针点刺出血或用皮肤针叩刺，然后将火罐吸拔在点刺的部位上，使之出血，加强刺血治疗的作用。 一般针后拔罐留置5~10分钟。\r\n\"\r\n",
                      "treatname": "æ\u0084\u009få\u0086\u0092\\æ\u009a\u0091æ¹¿ä¼¤è¡¨è¯\u0081",
                      "type": 3,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "attention": "当今在重新认识天然药物疗法和非药物疗法的优越性时， 推拿这一传统的不药而愈的治疗方法越来越为人们所重视。 目前推拿疗法已经被广泛应用与各种骨伤科疾病、 周围神经疾病及一些内妇儿疾病，均取得了很好的效果，在一些骨伤疾病，例如退行性脊柱病变、肩周炎、膝骨性关节炎等疾病的治疗上，推拿疗法已经成为第一首选疗法。\r\r\n ",
                      "days": 3,
                      "therapy":"清暑祛湿解表",
                      "effect": "推拿古称按摩、按跷等，是在中医基础理论基础指导下，运用推拿手法或借助于一定的推拿工具作用于人体体表的特定部位或穴位来防治疾病的一种治疗方法",
                      "freqid": 1,
                      "id": 2,
                      "itId": 79,
                      "modifyDate": 1534759668000,
                      "orgCode": "bg",
                      "position": "",
                      "stId": 7,
                      "stName": "拔罐",
                      "stars": 1,
                      "tcmImtreatprelistStAcupoints": [],
                      "tcmMatchingAcupoints": [],
                      "therapy": "\"（一）揉法\r\n用手掌根或手指面部分着力，吸定于一定的部位或穴位上，进行轻柔和缓揉动的一种手法， 称为揉法。 揉法一般分为鱼际揉、掌根揉和肘揉三种。\r\n手法要领：取站立或坐势，两手轮换操作，沉肩、垂肘，肘关节自然伸直或微屈， 大鱼际或掌根或手指面吸定于一定部位或穴位上，腕部放松，以肘部为支点，前臂作主动摆动，带动腕部或掌指作轻柔和缓的摆动。\r\n本法操作时要呼吸均匀、自然，不可屏气，压力要轻柔，动作要协调而有节律。 一般速度每分钟120~160次。\r\n \r\n图1 （1）掌根揉法（2）大鱼际揉\r\n \r\n图2 肘揉法\r\n（二）推法\r\n用指、 掌或肘部着力于一定的部位上进行单方向的直线或弧线移动，称为推法。有指推法、掌推法和肘推法三种。用指称指推法，用掌称掌推法，用肘称肘推法。\r\n手法要领：沉肩、垂肘，肘关节微屈或屈曲，腕部伸平或背伸。指、掌或肘要紧贴体表，用力要稳，速度要缓慢而均匀地做直线推动。操作时，动作要协调，不可硬压、死按，以防推破皮肤。在推动时不能耸肩，也不可左右滑动、忽快忽慢。\r\n \r\n图3 指推法\r\n \r\n图4 掌平推\r\n \r\n图5 分推法\r\n \r\n图6 肘平推（三）扌衮法\r\n用小指掌指关节背侧着力于一定的部位或穴位上， 通过前臂的旋转运动和腕关节的屈伸运动， 使之产生持续地作用于部位或穴位上的一种手法，称为扌衮法。\r\n手法要领：本法一般取站势，可单手操作亦可双手操作。 沉肩、垂肘，肘关节微屈约120度，置于身体侧前方。 腕部放松，用小指掌指关节背侧，附着在一定部位，以肘部为支点，前臂作主动摆动，带动腕部作伸屈和前臂旋转的复合运动。 操作时，手法吸定的部位要紧贴体表，不能拖动或跳动。压力、频率、摆动幅度要均匀，动作要协调而有节律，扌衮动频率每分钟120~160次。\r\n \r\n图7 扌衮法\r\n \r\n图8 掌指关节着力的扌衮法（四）按法\r\n以指或掌按压一定穴位或部位，逐渐用力，按而留之的一种手法，称按法。 有指按法和掌按法两种。\r\n手法要领：沉肩、垂肘，肘关节微屈或屈曲，腕关节掌屈，拇指或中指伸直，余四指屈曲，以指面为着力部，为指按法曰或腕关节背伸，手指伸直，以手掌为着力部，用单掌或双掌，亦可用双掌重叠按压体表，为掌按法。 操作时着力部位要紧贴体表，不可移动，前臂静止发力，按而不动逐渐用力，使力深透，不可用暴力猛然按压。操作中应根据具体情况决定施力大小和操作时间。按法在临床上常与揉法结合应用，组成”按揉”复合手法应用。\r\n \r\n 图9 掌按法 图10 叠掌按法\r\n（五）拿法\r\n用拇指与其他手指指面为着力部对称用力， 夹持一定的穴位或部位，捏而提之谓之拿法。\r\n手法要领：沉肩、垂肘，肘关节屈曲，悬腕或腕关节自然掌屈或伸平，以指面为着力部、前臂静止性发力。 以腕关节与掌指关节的协调活动为主，大拇指和示、中两指，或用大拇指和其余四指作相对用力，在一定的部位和穴位上进行节律性地提捏。操作时，拿取的部位或穴位要准确，用劲要由轻而重，不可突然用力，动作要缓和而有连贯性。\r\n \r\n图11 拿法\r\n \r\n图12 拿肩颈及拿项部\r\n（六）点法\r\n以拇指指端或指间关节突起部着力于一定的部位或穴位上，按而压之，戳而点之，谓之点法。有拇指点和屈指点及肘点三种。\r\n手法要领：沉肩、垂肘，肘关节伸直或屈曲，腕部伸平或掌屈。 拇指点是用拇指端点压体表。 屈指点是屈拇指，用拇指指间关节桡侧点压体表，或屈示指近侧指间关节或用肘部点压体表。着力要固定，不得滑移，力量由轻逐渐加重，再逐渐减力，切忌暴力戳按。本法与按法的区别是：点法作用面积小，刺激量更大。点法在临床上常与揉法结合使用，组成点揉复合手法应用。\r\n \r\n图13 指点法\r\n \r\n图14 肘点法\r\n（七）拍法\r\n用虚掌或拍子，拍打体表的一种手法，称为拍法，又称拍打法。\r\n手法要领：上肢放松，肘关节微屈，腕部背伸，手指自然并拢，掌指关节微屈呈虚掌，以肩关节活动为主，带动肘关节屈曲与腕关节悬屈、背伸的活动。 拍打时要平稳而有节律，拍打的部位要准确，用力要先轻后重。 拍法多用于腰骶、大腿、上臂等部。\r\n \r\n图15 拍法（八）摇法\r\n用一手握住或夹住关节近端肢体， 另一手握住关节远端肢体，做缓和被动的环转活动的一种手法，称摇法。 因施术部位的不同而名称、操作各异。\r\n手法要领：摇法动作要缓和，用力要稳，摇动方向及幅度须在患者生理许可范围内进行，自小到大，顺其自然，因势利导，切忌动作粗暴和蛮干。\r\n \r\n图16 托肘摇肩法\r\n \r\n图17 握手摇肩法\r\n \r\n图18 肘关节摇法\r\n \r\n图19 腕关节摇法\r\n \r\n图20 腰部摇法\r\n \r\n图21 仰卧位腰椎摇法\r\n \r\n图22 髋关节摇法\r\n \r\n图23 膝关节摇法\r\n \r\n图24 摇踝特别提示：因颈椎摇法有一定的危险性暂不收入本书中。（九）拔伸法\r\n拔伸即牵拉、牵引的意思。拔伸法是指用两手分别握住肢体的远近端，做相反方向的牵拉曰或利用肢体自身的重量做反牵拉力，两手握住肢体远端，向上或向前牵拉的一种方法。手法要领：\r\n1、头颈部拔伸法：患者正坐。 医生站在患者背后，用双手拇指顶在枕骨下方，掌根托住两侧下颌角的下方，并用两前臂压住患者两肩，两手用力向上，两前臂下压，同时作相反方向用力。\r\n2、肩关节拔伸法：患者坐势，医生用双手握住其腕上部或肘部，逐渐用力牵拉拔伸，嘱患者身体向对侧倾斜（或有一助手帮助固定患者身体），以对抗牵拉。\r\n3、腕关节拔伸法：医生一手握住患者前臂下端，另一手握住其手部，两手同时作相反方向用力，逐渐牵拉拔伸。\r\n4、指间关节拔伸法：用一手捏住被拔伸关节的近侧端，另一手捏住其远侧端，两手同时作反方向用力牵引拔伸。 5、膝关节拔伸法受术者仰卧位，下肢自然伸直。术者双手握住一侧下肢的踝关节部，沿下肢的纵轴方向持续拔伸。\r\n6、踝关节拔伸法受术者仰卧位，术者用一手托住其足跟，另一手握住脚掌侧面或脚趾，两手同时用力，逐渐牵拉。\r\n本法操作时用力要均匀而持久，动作要缓和，拔伸强度要恰如其分，适可而止。\r\n \r\n图25 低坐位颈部拔伸\r\n \r\n图26 仰卧颈部拔伸\r\n \r\n图27 肩关节拔伸\r\n \r\n图28 腕关节拔伸\r\n \r\n图29 指间关节拔伸\r\n \r\n图30 腰部拔伸法\r\n \r\n图31 膝关节拔伸法\r\n \r\n图3圆 踝关节拔伸法\r\n特别提示： 因颈椎拔伸法有一定的危险性， 暂不收入本书中。\"\r\n",
                      "treatname": "æ\u0084\u009få\u0086\u0092\\æ\u009a\u0091æ¹¿ä¼¤è¡¨è¯\u0081",
                      "type": 3,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "attention": "灸法是以艾绒或以艾绒为主要成分制成的灸材， 点燃后悬置或放置在穴位或病变部位，借灸火的热力以及药物的作用，激发经气，达到防治疾病目的的一种外治方法。\r\n",
                      "days": 3,
                      "therapy":"清暑祛湿解表",
                      "effect": "灸法具有温经散寒、扶阳固脱、消瘀散结、防病保健的作用，常用于寒湿痹痛、脏腑虚寒、阳气虚脱、气虚下陷、经络瘀阻等证及亚健康调理。\r\n",
                      "freqid": 1,
                      "id": 4,
                      "itId": 79,
                      "modifyDate": 1534814315000,
                      "orgCode": "bg",
                      "position": "",
                      "stId": 2,
                      "stName": "拔罐",
                      "stars": 1,
                      "tcmImtreatprelistStAcupoints": [],
                      "tcmMatchingAcupoints": [],
                      "therapy": "\"（一）隔物灸：是指用药物或其他材料将艾炷（用艾绒制成的圆锥形小体称为艾炷，一般锥体高 厘米左右，锥体直径0.8厘米左右，燃烧一炷即为一壮）与施灸穴位的皮肤隔开进行施灸的方法。 目前常用的隔物灸有隔姜灸、隔蒜灸、隔盐灸等。\r\n2、隔盐灸：用纯净食盐填敷于脐部，或于盐上再置一薄姜片，上置大艾炷施灸，当患者感觉灼烫时，可将姜片稍提起，稍停后放下再灸，以免烫伤。 艾炷燃尽，易炷再灸，直至灸完应灸壮数。\r\n3、隔蒜灸：用鲜大蒜头，切成厚约0.3厘米~0.5厘米的薄片，中间以针刺数孔，然后置于应灸的穴位上或患处，再将艾炷放置于蒜片上点燃施灸，当患者感觉灼烫时，可将蒜片稍提起，稍停后放下再灸，以免烫伤。艾炷燃尽，易炷再灸，直至灸完应灸壮数。\r\n（二）悬灸：用点燃的艾条，对准施灸部位，距离皮肤3厘米~ 5厘米处熏烤，使患者局部感觉温热而无灼痛感，一般施灸时间\r\n10 15分钟。 常用的悬灸方法有温和灸、雀啄灸、回旋灸等。\r\n1、温和灸：用点燃的艾条，对准施灸部位，距离皮肤3厘米左右处熏烤，使患者局部感觉温热而无灼痛感，灸至皮肤潮红为度，一般施灸时间10分钟~15分钟。\r\n2、雀啄灸：用点燃的艾条，对准施灸部位一上一下地摆动，如鸟雀啄食一样，一般施灸时间5分钟~10分钟。 3、回旋灸：用点燃的艾条，与施灸部位皮肤保持一定距离，均匀地左右移动或往复回旋熏烤施灸。\r\n4、温盒灸：是将温灸盒置于所选的施灸部位中央，点燃艾条后，放在施灸穴位上方的灸盒中铁纱上，盖好封盖以调节温度，每次每部位灸20~30分钟，一次可艾灸数穴。\"\r\n",
                      "treatname": "æ\u0084\u009få\u0086\u0092\\æ\u009a\u0091æ¹¿ä¼¤è¡¨è¯\u0081",
                      "type": 3,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "attention": "刮痧疗法是用特制的刮痧器具，依据中医经络腧穴理论，在体表进行相应的手法刮拭，以防治疾病的方法。\r\n",
                      "days": 3,
                      "therapy":"清暑祛湿解表",
                      "effect": "刮痧疗法具有活血化瘀、改善血液循环，驱邪排毒、促进新陈代谢，益气扶正、调节免疫能力，理筋通络、调整关节结构和功能。 尤其对外感性疾病、疼痛性疾病、骨关节退行性疾病和神经、肌肉、血管性等疾病， 均有较好的防治效果。\r\n",
                      "freqid": 1,
                      "id": 19,
                      "itId": 79,
                      "modifyDate": 1534814503000,
                      "orgCode": "bg",
                      "position": "",
                      "stId": 4,
                      "stName": "拔罐",
                      "stars": 1,
                      "tcmImtreatprelistStAcupoints": [],
                      "tcmMatchingAcupoints": [],
                      "therapy": "\"（一）刮痧器具的选择\r\n根据病症和刮痧部位的不同， 选择相应的刮痧板和刮痧介质。\r\n1、刮痧板的选择\r\n（1）椭圆形刮痧板：呈椭圆形或月圆形，边缘光滑，宜用于人体脊柱双侧、腹部和四肢肌肉较丰满部位刮痧。\r\n（2）方形刮痧板：一侧薄而外凸为弧形，对侧厚而内凹为直线形 呈方形，宜用于人体躯干、四肢部位刮痧。\r\n（3）缺口形刮痧板：边缘设置有缺口，以扩大特殊部位的接触面积，减轻疼痛，宜用于手指、足趾、脊柱部位刮痧。\r\n（4）三角形刮痧板：呈三角形，棱角处便于点穴，宜用于胸背部肋间隙、四肢末端部位刮痧。（5）梳形刮痧板：呈梳子状，便于接触头皮，保护头发，宜用于头部刮痧。 、刮痧介质的选择\r\n（1）刮痧油是中草药与医用油精炼而成的油剂，具有清热解毒、活血化瘀、解肌发表、缓解疼痛、帮助透痧，以及润滑护肤增效等作用。 宜用于成人刮痧，或刮痧面积大者，或皮肤干燥者。（2）刮痧乳是天然植物合成的乳剂，具有改善血液循环、促进新陈代谢、润滑护肤增效的作用。 宜用于儿童刮痧，或面部刮痧，或拔罐进行走罐时。（二）握持刮痧板方法\r\n根据所选刮痧板的形状和大小，使用便于操作的握板方法。一般为单手握板，将刮痧板放置掌心，一侧由拇指固定，另一侧由食指和中指固定，或由拇指以外的其余四指固定（图1）。 刮痧时利用指力和腕力使刮痧板与皮肤之间夹角约45毅为宜。\r\n \r\n图1 握板方法（三）刮痧的次序\r\n选择刮痧部位顺序的总原则为先头面后手足， 先胸腹后背腰，先上肢后下肢，逐步按顺序刮痧。 全身刮痧者，顺序为：头、颈、肩、上肢、胸腹、背腰及下肢曰局部刮痧者，如颈部刮痧顺序为头、颈、肩、上肢曰肩部刮痧顺序为头、颈、肩上、肩前、肩后、上肢曰背腰部刮痧顺序为背腰部正中、脊柱两侧、双下肢。（四）刮痧的方向总原则为由上向下，由内向外，单方向刮拭，尽可能拉长距离。 头部一般采用梳头法，由前向后（图2）曰面部一般由正中向两侧，下颌向外上刮拭（图3）曰胸部正中应由上向下，肋间则应由内向外（图4）曰背部、腰部、腹部则应由上向下，逐步由内向外扩展（图5、6、7）曰四肢宜向末梢方向刮拭（图8、9）。\r\n图3 面部刮拭方向 图4 胸部刮拭方向 图5 腹部刮拭方向\r\n \r\n图6 肩背部刮拭方向 图7 背部刮拭方向\r\n \r\n 图8 上肢刮拭方向 图9 下肢刮痧方向\r\n（五）刮痧的补泻方法刮痧的补泻方法为临床常用的综合手法，可分为：\r\n1、 刮痧补法：刮痧时，刮痧板按压的力度（力量）小，刮拭速度慢，刮拭时间相对较长。 此法宜用于体弱多病、久病虚弱的虚证患者，或对疼痛敏感者等。\r\n2、 刮痧泻法：刮痧时，刮痧板按压的力度（力量）大，刮拭速度快，刮拭时间相对较短。 此法宜用于身体强壮、疾病初期的实证患者以及骨关节疼痛患者。\r\n3、 刮痧平补平泻法：介于刮痧补法和刮痧泻法之间。 刮痧时，刮痧板按压的力度和速度适中，时间因人而异。 此法宜用于虚实夹杂体质的患者， 尤其适宜于亚健康人群或慢性病患者的康复刮痧。（六）刮痧的时间\r\n刮痧的时间包括每次治疗时间、刮痧间隔和疗程：\r\n1、每个部位一般刮拭20~30次，通常一个患者选3~5个部位曰局部刮痧一般10~20分钟，全身刮痧宜20~30分钟。\r\n2、两次刮痧之间宜间隔3~6天，或以皮肤上痧退、手压皮肤无痛感为宜曰若病情需要，或刮痧部位的痧斑未退，不宜在原部位进行刮拭，可另选其它相关部位进行刮痧。\r\n3、急性病痊愈为止，一般慢性病以7~10次为一疗程。\r\n（七）刮痧的程度刮痧的程度包括刮拭的力量强度和出痧程度：\r\n、\r\n 刮痧时用力要均匀，由轻到重，以能够承受为度。\r\n2、一般刮至皮肤出现潮红、紫红色等颜色变化，或出现粟粒状、丘疹样斑点，或片状、条索状斑块等形态变化，并伴有局部热感或轻微疼痛。对一些不易出痧或出痧较少的患者，不可强求出痧。\r\n（八）刮痧手法\r\n根据病证和刮痧部位的不同，刮痧操作的力量大小、速度快慢、刮拭方向、刮痧板边角接触的部位以及刮痧配合手法应有所不同。刮痧手法分类如下： 、按力量大小分类\r\n（1）轻刮法：刮痧时刮痧板接触皮肤下压刮拭的力量小，被刮者无疼痛及其他不适感觉。 轻刮后皮肤仅出现微红，无瘀斑。此法宜用于老年体弱者、 疼痛敏感部位以及辨证属于虚证的患者。\r\n（2）重刮法：刮痧时刮痧板接触皮肤下压刮拭的力量较大，以患者能承受为度。此法宜用于腰背部脊柱两侧、下肢软组织较丰富处、青壮年体质较强者以及辨证属于实证、热证的患者。 、按移动速度分类\r\n 1）快刮法：刮拭的频率在每分钟30次以上。此法宜用于体质强壮者，主要用于刮拭背部、四肢以及辨证属于急性、外感病证的患者。\r\n（2）慢刮法：刮拭的频率在每分钟30次以内。此法宜用于体质虚弱者，主要用于刮拭头面部、胸部、腹部、下肢内侧等部位以及辨证属于内科、体虚的慢性病患者。 、按刮拭方向分类\r\n（1）直线刮法：又称直板刮法。 用刮痧板在人体体表进行有一定长度的直线刮拭。 此法宜用于身体比较平坦的部位， 如背部、胸腹部、四肢部位。\r\n（2）弧线刮法：刮拭方向呈弧线形，刮拭后体表出现弧线形的痧痕， 操作时刮痧方向多循肌肉走行或根据骨骼结构特点而定。此法宜用于胸背部肋间隙、肩关节和膝关节周围等部位。 、按刮痧板接触体表部位分类\r\n（1）摩擦法：将刮痧板与皮肤直接紧贴，或隔衣布进行有规律的旋转移动，或直线式往返移动，使皮肤产生热感。 此法宜用于麻木、发凉或绵绵隐痛的部位，如肩胛内侧、腰部和腹部曰也可用于刮痧前，使患者放松。\r\n（2）梳刮法：使用刮痧板或刮痧梳从前额发际处及双侧太阳穴处向后发际处做有规律的单方向刮拭， 刮痧板或刮痧梳与头皮呈45毅角，动作宜轻柔和缓，如梳头状，故名梳刮法。 此法宜用于头痛、头晕、疲劳、失眠和精神紧张等病证。\r\n（3）点压法：又称点穴手法。用刮痧板的边角直接点压穴位，力量逐渐加重，以患者能承受为度，保持数秒后快速抬起，重复操作5~10次。 此法宜用于肌肉丰满处的穴位，或刮痧力量不能深达，或不宜直接刮拭的骨骼关节凹陷部位，如环跳、委中、犊鼻、水沟和背部脊柱棘突之间等。\r\n（4）按揉法：刮痧板在穴位处做点压按揉，点下后做往返来回或顺逆旋转。 操作时刮痧板应紧贴皮肤不滑动， 每分钟按揉 50~100次。 此法宜用于太阳、曲池、足三里、内关、太冲、涌泉、三\r\n阴交等穴位。（5）角刮法：使用角形刮痧板或让刮痧板的棱角接触皮肤，与体表成45毅角，自上而下或由里向外刮拭。 手法要灵活，不宜生硬，避免用力过猛而损伤皮肤。 此法宜用于四肢关节、脊柱两侧经筋部位、骨突周围、肩部穴位，如风池、内关、合谷、中府等。（6）边刮法：将刮痧板的长条棱边，与体表接触成45毅角进行刮拭。 此法宜用于对大面积部位的刮拭，如腹部、背部和下肢等。\r\n\"\r\n",
                      "treatname": "æ\u0084\u009få\u0086\u0092\\æ\u009a\u0091æ¹¿ä¼¤è¡¨è¯\u0081",
                      "type": 3,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "attention": "灸法是以艾绒或以艾绒为主要成分制成的灸材， 点燃后悬置或放置在穴位或病变部位，借灸火的热力以及药物的作用，激发经气，达到防治疾病目的的一种外治方法。\r\n",
                      "days": 3,
                      "therapy":"清暑祛湿解表",
                      "effect": "灸法具有温经散寒、扶阳固脱、消瘀散结、防病保健的作用，常用于寒湿痹痛、脏腑虚寒、阳气虚脱、气虚下陷、经络瘀阻等证及亚健康调理。\r\n",
                      "freqid": 1,
                      "id": 3,
                      "itId": 66,
                      "modifyDate": 1534814314000,
                      "orgCode": "bg",
                      "position": "",
                      "stId": 2,
                      "stName": "拔罐",
                      "stars": 1,
                      "tcmImtreatprelistStAcupoints": [],
                      "tcmMatchingAcupoints": [],
                      "therapy": "\"（一）隔物灸：是指用药物或其他材料将艾炷（用艾绒制成的圆锥形小体称为艾炷，一般锥体高 厘米左右，锥体直径0.8厘米左右，燃烧一炷即为一壮）与施灸穴位的皮肤隔开进行施灸的方法。 目前常用的隔物灸有隔姜灸、隔蒜灸、隔盐灸等。\r\n2、隔盐灸：用纯净食盐填敷于脐部，或于盐上再置一薄姜片，上置大艾炷施灸，当患者感觉灼烫时，可将姜片稍提起，稍停后放下再灸，以免烫伤。 艾炷燃尽，易炷再灸，直至灸完应灸壮数。\r\n3、隔蒜灸：用鲜大蒜头，切成厚约0.3厘米~0.5厘米的薄片，中间以针刺数孔，然后置于应灸的穴位上或患处，再将艾炷放置于蒜片上点燃施灸，当患者感觉灼烫时，可将蒜片稍提起，稍停后放下再灸，以免烫伤。艾炷燃尽，易炷再灸，直至灸完应灸壮数。\r\n（二）悬灸：用点燃的艾条，对准施灸部位，距离皮肤3厘米~ 5厘米处熏烤，使患者局部感觉温热而无灼痛感，一般施灸时间\r\n10 15分钟。 常用的悬灸方法有温和灸、雀啄灸、回旋灸等。\r\n1、温和灸：用点燃的艾条，对准施灸部位，距离皮肤3厘米左右处熏烤，使患者局部感觉温热而无灼痛感，灸至皮肤潮红为度，一般施灸时间10分钟~15分钟。\r\n2、雀啄灸：用点燃的艾条，对准施灸部位一上一下地摆动，如鸟雀啄食一样，一般施灸时间5分钟~10分钟。 3、回旋灸：用点燃的艾条，与施灸部位皮肤保持一定距离，均匀地左右移动或往复回旋熏烤施灸。\r\n4、温盒灸：是将温灸盒置于所选的施灸部位中央，点燃艾条后，放在施灸穴位上方的灸盒中铁纱上，盖好封盖以调节温度，每次每部位灸20~30分钟，一次可艾灸数穴。\"\r\n",
                      "treatname": "è\u0099\u009aå\u008a³\\å¿\u0083é\u0098³è\u0099\u009aè¯\u0081",
                      "type": 3,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "attention": "刮痧疗法是用特制的刮痧器具，依据中医经络腧穴理论，在体表进行相应的手法刮拭，以防治疾病的方法。\r\n",
                      "days": 3,
                      "therapy":"清暑祛湿解表",
                      "effect": "刮痧疗法具有活血化瘀、改善血液循环，驱邪排毒、促进新陈代谢，益气扶正、调节免疫能力，理筋通络、调整关节结构和功能。 尤其对外感性疾病、疼痛性疾病、骨关节退行性疾病和神经、肌肉、血管性等疾病， 均有较好的防治效果。\r\n",
                      "freqid": 1,
                      "id": 6,
                      "itId": 5,
                      "modifyDate": 1534814566000,
                      "orgCode": "bg",
                      "position": "",
                      "stId": 4,
                      "stName": "拔罐",
                      "stars": 1,
                      "tcmImtreatprelistStAcupoints": [],
                      "tcmMatchingAcupoints": [],
                      "therapy": "\"（一）刮痧器具的选择\r\n根据病症和刮痧部位的不同， 选择相应的刮痧板和刮痧介质。\r\n1、刮痧板的选择\r\n（1）椭圆形刮痧板：呈椭圆形或月圆形，边缘光滑，宜用于人体脊柱双侧、腹部和四肢肌肉较丰满部位刮痧。\r\n（2）方形刮痧板：一侧薄而外凸为弧形，对侧厚而内凹为直线形 呈方形，宜用于人体躯干、四肢部位刮痧。\r\n（3）缺口形刮痧板：边缘设置有缺口，以扩大特殊部位的接触面积，减轻疼痛，宜用于手指、足趾、脊柱部位刮痧。\r\n（4）三角形刮痧板：呈三角形，棱角处便于点穴，宜用于胸背部肋间隙、四肢末端部位刮痧。（5）梳形刮痧板：呈梳子状，便于接触头皮，保护头发，宜用于头部刮痧。 、刮痧介质的选择\r\n（1）刮痧油是中草药与医用油精炼而成的油剂，具有清热解毒、活血化瘀、解肌发表、缓解疼痛、帮助透痧，以及润滑护肤增效等作用。 宜用于成人刮痧，或刮痧面积大者，或皮肤干燥者。（2）刮痧乳是天然植物合成的乳剂，具有改善血液循环、促进新陈代谢、润滑护肤增效的作用。 宜用于儿童刮痧，或面部刮痧，或拔罐进行走罐时。（二）握持刮痧板方法\r\n根据所选刮痧板的形状和大小，使用便于操作的握板方法。一般为单手握板，将刮痧板放置掌心，一侧由拇指固定，另一侧由食指和中指固定，或由拇指以外的其余四指固定（图1）。 刮痧时利用指力和腕力使刮痧板与皮肤之间夹角约45毅为宜。\r\n \r\n图1 握板方法（三）刮痧的次序\r\n选择刮痧部位顺序的总原则为先头面后手足， 先胸腹后背腰，先上肢后下肢，逐步按顺序刮痧。 全身刮痧者，顺序为：头、颈、肩、上肢、胸腹、背腰及下肢曰局部刮痧者，如颈部刮痧顺序为头、颈、肩、上肢曰肩部刮痧顺序为头、颈、肩上、肩前、肩后、上肢曰背腰部刮痧顺序为背腰部正中、脊柱两侧、双下肢。（四）刮痧的方向总原则为由上向下，由内向外，单方向刮拭，尽可能拉长距离。 头部一般采用梳头法，由前向后（图2）曰面部一般由正中向两侧，下颌向外上刮拭（图3）曰胸部正中应由上向下，肋间则应由内向外（图4）曰背部、腰部、腹部则应由上向下，逐步由内向外扩展（图5、6、7）曰四肢宜向末梢方向刮拭（图8、9）。\r\n图3 面部刮拭方向 图4 胸部刮拭方向 图5 腹部刮拭方向\r\n \r\n图6 肩背部刮拭方向 图7 背部刮拭方向\r\n \r\n 图8 上肢刮拭方向 图9 下肢刮痧方向\r\n（五）刮痧的补泻方法刮痧的补泻方法为临床常用的综合手法，可分为：\r\n1、 刮痧补法：刮痧时，刮痧板按压的力度（力量）小，刮拭速度慢，刮拭时间相对较长。 此法宜用于体弱多病、久病虚弱的虚证患者，或对疼痛敏感者等。\r\n2、 刮痧泻法：刮痧时，刮痧板按压的力度（力量）大，刮拭速度快，刮拭时间相对较短。 此法宜用于身体强壮、疾病初期的实证患者以及骨关节疼痛患者。\r\n3、 刮痧平补平泻法：介于刮痧补法和刮痧泻法之间。 刮痧时，刮痧板按压的力度和速度适中，时间因人而异。 此法宜用于虚实夹杂体质的患者， 尤其适宜于亚健康人群或慢性病患者的康复刮痧。（六）刮痧的时间\r\n刮痧的时间包括每次治疗时间、刮痧间隔和疗程：\r\n1、每个部位一般刮拭20~30次，通常一个患者选3~5个部位曰局部刮痧一般10~20分钟，全身刮痧宜20~30分钟。\r\n2、两次刮痧之间宜间隔3~6天，或以皮肤上痧退、手压皮肤无痛感为宜曰若病情需要，或刮痧部位的痧斑未退，不宜在原部位进行刮拭，可另选其它相关部位进行刮痧。\r\n3、急性病痊愈为止，一般慢性病以7~10次为一疗程。\r\n（七）刮痧的程度刮痧的程度包括刮拭的力量强度和出痧程度：\r\n、\r\n 刮痧时用力要均匀，由轻到重，以能够承受为度。\r\n2、一般刮至皮肤出现潮红、紫红色等颜色变化，或出现粟粒状、丘疹样斑点，或片状、条索状斑块等形态变化，并伴有局部热感或轻微疼痛。对一些不易出痧或出痧较少的患者，不可强求出痧。\r\n（八）刮痧手法\r\n根据病证和刮痧部位的不同，刮痧操作的力量大小、速度快慢、刮拭方向、刮痧板边角接触的部位以及刮痧配合手法应有所不同。刮痧手法分类如下： 、按力量大小分类\r\n（1）轻刮法：刮痧时刮痧板接触皮肤下压刮拭的力量小，被刮者无疼痛及其他不适感觉。 轻刮后皮肤仅出现微红，无瘀斑。此法宜用于老年体弱者、 疼痛敏感部位以及辨证属于虚证的患者。\r\n（2）重刮法：刮痧时刮痧板接触皮肤下压刮拭的力量较大，以患者能承受为度。此法宜用于腰背部脊柱两侧、下肢软组织较丰富处、青壮年体质较强者以及辨证属于实证、热证的患者。 、按移动速度分类\r\n 1）快刮法：刮拭的频率在每分钟30次以上。此法宜用于体质强壮者，主要用于刮拭背部、四肢以及辨证属于急性、外感病证的患者。\r\n（2）慢刮法：刮拭的频率在每分钟30次以内。此法宜用于体质虚弱者，主要用于刮拭头面部、胸部、腹部、下肢内侧等部位以及辨证属于内科、体虚的慢性病患者。 、按刮拭方向分类\r\n（1）直线刮法：又称直板刮法。 用刮痧板在人体体表进行有一定长度的直线刮拭。 此法宜用于身体比较平坦的部位， 如背部、胸腹部、四肢部位。\r\n（2）弧线刮法：刮拭方向呈弧线形，刮拭后体表出现弧线形的痧痕， 操作时刮痧方向多循肌肉走行或根据骨骼结构特点而定。此法宜用于胸背部肋间隙、肩关节和膝关节周围等部位。 、按刮痧板接触体表部位分类\r\n（1）摩擦法：将刮痧板与皮肤直接紧贴，或隔衣布进行有规律的旋转移动，或直线式往返移动，使皮肤产生热感。 此法宜用于麻木、发凉或绵绵隐痛的部位，如肩胛内侧、腰部和腹部曰也可用于刮痧前，使患者放松。\r\n（2）梳刮法：使用刮痧板或刮痧梳从前额发际处及双侧太阳穴处向后发际处做有规律的单方向刮拭， 刮痧板或刮痧梳与头皮呈45毅角，动作宜轻柔和缓，如梳头状，故名梳刮法。 此法宜用于头痛、头晕、疲劳、失眠和精神紧张等病证。\r\n（3）点压法：又称点穴手法。用刮痧板的边角直接点压穴位，力量逐渐加重，以患者能承受为度，保持数秒后快速抬起，重复操作5~10次。 此法宜用于肌肉丰满处的穴位，或刮痧力量不能深达，或不宜直接刮拭的骨骼关节凹陷部位，如环跳、委中、犊鼻、水沟和背部脊柱棘突之间等。\r\n（4）按揉法：刮痧板在穴位处做点压按揉，点下后做往返来回或顺逆旋转。 操作时刮痧板应紧贴皮肤不滑动， 每分钟按揉 50~100次。 此法宜用于太阳、曲池、足三里、内关、太冲、涌泉、三\r\n阴交等穴位。（5）角刮法：使用角形刮痧板或让刮痧板的棱角接触皮肤，与体表成45毅角，自上而下或由里向外刮拭。 手法要灵活，不宜生硬，避免用力过猛而损伤皮肤。 此法宜用于四肢关节、脊柱两侧经筋部位、骨突周围、肩部穴位，如风池、内关、合谷、中府等。（6）边刮法：将刮痧板的长条棱边，与体表接触成45毅角进行刮拭。 此法宜用于对大面积部位的刮拭，如腹部、背部和下肢等。\r\n\"\r\n",
                      "treatname": "æ¶\u0088æ¸´\\è\u0082ºç\u0083\u00adæ´¥ä¼¤è¯\u0081",
                      "type": 3,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "attention": "1",
                      "createDate": 1534471055000,
                      "days": 1,
                      "therapy":"清暑祛湿解表",
                      "effect": "1",
                      "freqid": 1,
                      "id": 7,
                      "itId": 5,
                      "modifyDate": 1534471368000,
                      "orgCode": "bg",
                      "position": "头部",
                      "stId": 1,
                      "stName": "拔罐",
                      "stars": 1,
                      "tcmImtreatprelistStAcupoints": [],
                      "tcmMatchingAcupoints": [],
                      "treatname": "æ¶\u0088æ¸´\\è\u0082ºç\u0083\u00adæ´¥ä¼¤è¯\u0081",
                      "type": 3,
                      "useflag": "1",
                      "visitCount": 0
                  },
                  {
                      "attention": "1",
                      "createDate": 1534471103000,
                      "days": 1,
                      "therapy":"清暑祛湿解表",
                      "effect": "1",
                      "freqid": 1,
                      "id": 8,
                      "itId": 5,
                      "modifyDate": 1534471294000,
                      "orgCode": "bg",
                      "position": "背部",
                      "stId": 2,
                      "stName": "拔罐",
                      "stars": 1,
                      "tcmImtreatprelistStAcupoints": [],
                      "tcmMatchingAcupoints": [],
                      "treatname": "æ¶\u0088æ¸´\\è\u0082ºç\u0083\u00adæ´¥ä¼¤è¯\u0081",
                      "type": 3,
                      "useflag": "1",
                      "visitCount": 0
                  }
              ],
              "pages": 2,
              "size": 8,
              "star": 0,
              "total": 10
          },
          "mlist": {
              "current": 1,
              "dataList": [
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  "null",
                  "null"
              ],
              "pages": 2,
              "size": 8,
              "star": 0,
              "total": 9
          }
      }
  }
  return QueryTypeData;
};


export { Simulation };
